project_name: vpn-dashboard
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
release:
  disable: true
