version: '3'

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    deps: [ install-fileb0x ]
    cmds:
      - goreleaser --snapshot --clean

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ install-go-mod-outdated, install-gomajor ]
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct
      #- gomajor list

  install-gomajor:
    cmds:
      - go install github.com/icholy/gomajor@v0.9.5
    status:
      - rtx which gomajor

  install-go-mod-outdated:
    cmds:
      - go install github.com/psampaz/go-mod-outdated@v0.9.0
    status:
      - rtx which go-mod-outdated

  install-fileb0x:
    cmds:
      - go install github.com/UnnoTed/fileb0x@v1.1.4
    status:
      - rtx which fileb0x
