version: '3'

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser release --auto-snapshot --clean

  generate:
    deps: [ generate-ui ]

  generate-ui:
    cmds:
      - cd ../ui && mise exec -- task build
      - rm -rf resources/ui
      - mkdir -p resources/ui
      - cp -r ../ui/dist/* resources/ui

  outdated:
    desc: Show dependency updates
    aliases: [ dependencyUpdates ]
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct
