version: '3'

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    deps: [ generate-ui ]
    cmds:
      - goreleaser --snapshot --clean

  generate-ui:
    cmds:
      - cd ../ui && eval `mise env` && task build
      - rm -rf resources/ui
      - mkdir -p resources/ui
      - cp -r ../ui/dist/* resources/ui

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ install-go-mod-outdated, install-gomajor ]
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct
      #- gomajor list

  install-gomajor:
    cmds:
      - go install github.com/icholy/gomajor@v0.9.5

  install-go-mod-outdated:
    cmds:
      - go install github.com/psampaz/go-mod-outdated@v0.9.0
