allowBuilds:
  '@parcel/watcher': false
  svelte-preprocess: false
minimumReleaseAgeExclude:
  - shell-quote@1.8.5
  - immutable@5.1.8
overrides:
  immutable@>=5.0.0-beta.1 <5.1.8: ^5.1.8
  shell-quote@<=1.8.4: ^1.8.5
