version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  install:
    cmds:
      - pnpm install
      - pnpm prune
    sources:
      - package.json
      - pnpm-lock.yaml
    generates:
      - node_modules/*

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build
    sources:
      - public/*
      - public/**/*
      - src/*
      - src/**/*
      - .env
      - index.html
      - package.json
      - svelte.config.js
      - pnpm-lock.yaml
      - tsconfig.json
      - tsconfig.node.json
      - vite.config.ts
    generates:
      - dist/*
      - dist/**/*

  run:
    deps: [ install ]
    cmds:
      - pnpm run dev

  dependencyUpdates:
    cmds:
      - cmd: pnpm outdated
        ignore_error: true
      - cmd: pnpm outdated --compatible
        ignore_error: true
