version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  install:
    cmds:
      - pnpm install
      - pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build

  run:
    deps: [ install ]
    cmds:
      - pnpm run dev

  outdated:
    desc: Outdated
    aliases: [ dependencyUpdates ]
    deps: [ install ]
    cmds:
      - cmd: pnpm outdated
        ignore_error: true
      - cmd: pnpm outdated --compatible
        ignore_error: true
