name: Build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.24"

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          working_directory: ./app
          experimental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: mise setup
        uses: jdx/mise-action@v2
        with:
          working_directory: ./ui
          experimental: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: "!startsWith(github.ref, 'refs/tags/')"
        working-directory: ./app
        run: goreleaser --snapshot --clean

      - name: Release
        if: "startsWith(github.ref, 'refs/tags/')"
        run: goreleaser release --clean
        working-directory: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
